"""Simplify subscription for graduated tiered pricing

Revision ID: 3f1f1bf8b240
Revises: f148a5bbb1f2
Create Date: 2025-12-05 16:09:14.816282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3f1f1bf8b240"
down_revision: Union[str, Sequence[str], None] = "f148a5bbb1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_subscriptions",
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        schema="public",
    )
    op.add_column(
        "user_subscriptions",
        sa.Column("stripe_subscription_item_id", sa.String(), nullable=True),
        schema="public",
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "current_period_usage", sa.BigInteger(), nullable=False, server_default="0"
        ),
        schema="public",
    )
    op.add_column(
        "user_subscriptions",
        sa.Column(
            "included_units", sa.BigInteger(), nullable=False, server_default="0"
        ),
        schema="public",
    )
    op.add_column(
        "user_subscriptions",
        sa.Column("billing_period_start", postgresql.TIMESTAMP(), nullable=True),
        schema="public",
    )
    op.add_column(
        "user_subscriptions",
        sa.Column("billing_period_end", postgresql.TIMESTAMP(), nullable=True),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_subscriptions", "billing_period_end", schema="public")
    op.drop_column("user_subscriptions", "billing_period_start", schema="public")
    op.drop_column("user_subscriptions", "included_units", schema="public")
    op.drop_column("user_subscriptions", "current_period_usage", schema="public")
    op.drop_column("user_subscriptions", "stripe_subscription_item_id", schema="public")
    op.drop_column("user_subscriptions", "stripe_subscription_id", schema="public")
    # ### end Alembic commands ###
