"""Initialization of alembic by eito

Revision ID: 54eeece17890
Revises:
Create Date: 2025-03-21 18:56:26.807211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "54eeece17890"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_products",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("default_price", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated", sa.TIMESTAMP(), nullable=True),
        sa.Column("attrs", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
        fdw_options={"object": "products", "rowid_column": "id"},
        fdw_server="stripe_server",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stripe_products", schema="public")
    # ### end Alembic commands ###
